
import { Integration } from "./types";

export const integrationsData: Integration[] = [
  {
    id: "revelator-api",
    name: "Revelator API",
    description: "The Revelator API is an all-in-one engine for building, scaling, and powering next-generation music platforms. Built for developers and tailored for the needs of modern music businesses, it lets you deliver and distribution digital music, automate royalty workflows, streamline metadata, rights, and reporting in real time, and integrate seamlessly with your existing tech stack.",
    provider: "Revelator",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["Rights, Royalties & Payment API", "Delivery & Distribution API"],
    languages: ["JavaScript"],
    tags: ["api", "metadata", "catalog-management"],
    category: "Rights & Royalties"
  },
  {
    id: "acoustid-api",
    name: "AcoustID API",
    description: "Open source audio fingerprinting service providing music identification through acoustic fingerprints and metadata lookup.",
    provider: "AcoustID",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Audio fingerprinting", "Music identification", "MusicBrainz integration"],
    languages: ["REST", "JSON"],
    tags: ["fingerprinting", "identification", "open-source"],
    category: "Music Recognition"
  },
  {
    id: "eventful-api",
    name: "Eventful API",
    description: "Events discovery API providing access to concerts, festivals, and live music events data for location-based music applications.",
    provider: "Eventful",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Event discovery", "Location-based search", "Concert listings"],
    languages: ["REST", "JSON", "XML"],
    tags: ["events", "concerts", "festivals"],
    category: "Events & Concerts"
  },
  {
    id: "songkick-api",
    name: "Songkick API",
    description: "Concert discovery platform with API access to live music events, artist tour dates, and venue information worldwide.",
    provider: "Songkick",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Concert tracking", "Artist tour dates", "Venue information"],
    languages: ["REST", "JSON"],
    tags: ["concerts", "tours", "venues"],
    category: "Events & Concerts"
  },
  {
    id: "bandsintown-api",
    name: "Bandsintown API",
    description: "Artist event management platform with API for accessing concert listings, tour dates, and fan engagement data.",
    provider: "Bandsintown",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Event management", "Tour promotion", "Fan tracking"],
    languages: ["REST", "JSON"],
    tags: ["events", "tours", "artists"],
    category: "Events & Concerts"
  },
  {
    id: "bandcamp-api",
    name: "Bandcamp Developer API",
    description: "OAuth 2.0-authenticated API platform for labels and merchandise fulfillment partners to interact with Bandcamp accounts. Provides programmatic access to account management, sales reporting, and merchandise order processing for the independent music community.",
    provider: "Bandcamp",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["Account API", "Sales Report API", "Merch Orders API"],
    languages: ["REST API"],
    tags: ["music-platform-api", "oauth2", "sales-reporting"],
    category: "Distribution & Sales"
  },
  {
    id: "shazamkit-api",
    name: "ShazamKit API",
    description: "Apple's music recognition developer platform enabling integration of Shazam's extensive music catalog into apps across Apple platforms and Android. Allows building custom audio catalogs, syncing with Shazam app, and creating audio-based experiences for music discovery and recognition.",
    provider: "Apple Inc.",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Music recognition", "Custom audio catalogs", "Cross-platform support"],
    languages: ["Swift", "Objective-C", "Java", "Kotlin"],
    tags: ["music-recognition", "audio-recognition", "developer-platform"],
    category: "Music Recognition"
  },
  {
    id: "quansic-api",
    name: "Quansic API",
    description: "Comprehensive music identifier registration platform operating as Registration Agency for Musical Works (BOWI), Sound Recordings (ISRC), and Parties (ISNI). RIAA-approved ISRC manager and ISNI Registration Agency providing APIs for automatic identifier assignment and bulk registration services.",
    provider: "Quansic",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["ISRC assignment", "ISNI registration", "BOWI work identifiers"],
    languages: ["REST API"],
    tags: ["music-identifiers", "isrc-registration", "isni-registration"],
    category: "Rights & Royalties"
  },
  {
    id: "imdb-api",
    name: "IMDb Developer API",
    description: "Premier source of global entertainment metadata featuring 10+ million titles, 14+ million cast and crew profiles, and 1.6+ billion ratings from the world's largest entertainment fan community. Offers GraphQL-backed API via AWS Data Exchange with daily updates and comprehensive box office data from Box Office Mojo.",
    provider: "IMDb",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["10+ million titles", "14+ million cast/crew", "1.6+ billion ratings"],
    languages: ["GraphQL API"],
    tags: ["entertainment-metadata", "movie-database", "tv-data"],
    category: "Metadata & Database"
  },
  {
    id: "luminate-data-api",
    name: "Luminate Data API",
    description: "Entertainment industry's most comprehensive data and insights platform providing validated music, film, and television consumption data and metadata. Offers Music API with data from 63 territories, Streaming Viewership API for major U.S. platforms, and Film & TV APIs serving record labels, publishers, streaming services, and entertainment companies.",
    provider: "Luminate Data, LLC",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["Music consumption data", "Streaming viewership metrics", "Entertainment metadata"],
    languages: ["REST API"],
    tags: ["entertainment-data", "music-consumption", "streaming-data"],
    category: "Analytics & Data"
  },
  {
    id: "elevenlabs-api",
    name: "ElevenLabs API",
    description: "Advanced AI voice synthesis platform providing realistic text-to-speech and voice cloning capabilities. While primarily for speech, offers high-quality voice generation technology applicable to music and creative projects.",
    provider: "ElevenLabs",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: ["Advanced voice synthesis", "Voice cloning", "Realistic speech generation"],
    languages: ["REST API"],
    tags: ["ai-voice-synthesis", "text-to-speech", "voice-cloning"],
    category: "AI & Voice"
  },
  {
    id: "tidal-api",
    name: "Tidal Developer API",
    description: "High-quality music streaming API providing access to Tidal's extensive catalog of lossless audio, exclusive content, and music metadata. Enables developers to integrate premium music streaming capabilities into applications with support for high-fidelity audio.",
    provider: "Tidal",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["Lossless audio streaming", "Music metadata", "Playlist management"],
    languages: ["REST API"],
    tags: ["music-streaming", "lossless-audio", "high-fidelity"],
    category: "Streaming & Playback"
  },
  {
    id: "discogs-api",
    name: "Discogs API",
    description: "Comprehensive music database and marketplace featuring detailed discography information, release data, and artist credits. Provides extensive music metadata, catalog management, and marketplace functionality for collectors and music industry professionals.",
    provider: "Discogs",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: ["Music database", "Release information", "Artist credits"],
    languages: ["REST API"],
    tags: ["music-database", "discography", "marketplace"],
    category: "Metadata & Database"
  },
  {
    id: "music-ai-api",
    name: "Music AI API",
    description: "Enterprise AI music analysis platform providing advanced music intelligence, analysis, and processing capabilities through both API and embedded SDK solutions for music industry professionals.",
    provider: "Music AI",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["AI music analysis", "Embedded SDK", "API integration"],
    languages: ["music.ai"],
    tags: ["ai-analysis", "music-intelligence"],
    category: "AI & Analysis"
  },
  {
    id: "soundverse-api",
    name: "Soundverse Enterprise API",
    description: "AI Music APIs with Zero legal headaches - Copyright-safe APIs in generative audio, backing every output with clear licensing, indemnification, and 99.9%-uptime SLAs. Enterprise-grade, plug-and-play audio stack, so that you can sleep well at night.",
    provider: "Soundverse",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["AI Music Generator", "AI Song Generator", "Stem Splitter"],
    languages: ["Python", "JavaScript", "Go", "C#"],
    tags: ["api", "audio-processing", "synthesis"],
    category: "AI & Generation"
  },
  {
    id: "ircam-amplify-api",
    name: "Ircam Amplify API",
    description: "Comprehensive Audio-as-a-Service platform offering best-in-class audio algorithms from IRCAM-Centre Pompidou research lab. Features AI music detection, spatial audio conversion, stem separation, voice analysis, and music processing APIs for developers and creative industries.",
    provider: "Ircam Amplify",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["AI Music Detector", "Stereo to Spatial", "Stem Separator"],
    languages: ["REST API"],
    tags: ["audio-apis", "ai-detection", "spatial-audio"],
    category: "Audio Processing"
  },
  {
    id: "aims-api",
    name: "AIMS API",
    description: "Advanced AI search platform for music catalogs that understands sound, visual, lyrics, and deeper meaning. Provides prompt search, similarity search, lyrics search, video search, and tagging capabilities for music professionals.",
    provider: "AIMS API s. r. o.",
    pricing: "enterprise",
    rating: 1,
    reviews: 0,
    features: ["Prompt search", "Similarity search", "Lyrics search"],
    languages: ["REST API"],
    tags: ["ai-search", "music-discovery", "similarity-search"],
    category: "AI & Search"
  },
  {
    id: "lyricfind-api",
    name: "LyricFind API",
    description: "Leading lyrics licensing platform with 20+ years of experience, providing verified lyrics display, search, translations, and royalty management services to major streaming platforms worldwide.",
    provider: "LyricFind",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["Static lyrics display", "Line-by-line sync", "Word-by-word sync"],
    languages: ["REST API"],
    tags: ["lyrics-licensing", "music-metadata", "lyrics-display"],
    category: "Lyrics & Text"
  },
  {
    id: "audioshake-api",
    name: "AudioShake API",
    description: "Industry-leading AI-powered audio separation platform providing stem creation, dialogue separation, and lyric transcription services for music production, sync licensing, and content creation.",
    provider: "AudioShake, Inc.",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["Instrument stem separation", "Dialogue-music-effects separation", "Multi-speaker separation"],
    languages: ["REST API", "Python SDK"],
    tags: ["ai-audio-separation", "stem-separation", "dialogue-separation"],
    category: "Audio Processing"
  },
  {
    id: "tone-api",
    name: "Tone API",
    description: "Advanced spatial audio and immersive sound technology platform providing 3D audio processing, binaural rendering, and personalized audio experiences for music, gaming, and VR applications.",
    provider: "Tone Platform",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["3D audio processing", "Binaural rendering", "Personalized HRTF"],
    languages: ["REST API", "SDK"],
    tags: ["spatial-audio", "3d-audio", "binaural-rendering"],
    category: "Audio Processing"
  },
  {
    id: "harmix-api",
    name: "Harmix API",
    description: "AI-powered music analysis and recommendation platform providing harmonic analysis, key detection, and intelligent music matching services for DJs, producers, and music applications.",
    provider: "Harmix Technologies",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["Harmonic analysis", "Key detection", "BPM analysis"],
    languages: ["REST API"],
    tags: ["music-analysis", "harmonic-analysis", "key-detection"],
    category: "AI & Analysis"
  },
  {
    id: "figaro-api",
    name: "Figaro API",
    description: "Advanced music intelligence platform providing AI-powered music analysis, emotion detection, and content classification services for music supervisors, brands, and content creators.",
    provider: "Figaro AI",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["Music emotion analysis", "Content classification", "Brand matching"],
    languages: ["REST API"],
    tags: ["music-intelligence", "emotion-detection", "content-classification"],
    category: "AI & Analysis"
  },
  {
    id: "music-story-api",
    name: "Music Story API",
    description: "Comprehensive music metadata and biography platform providing detailed artist information, discographies, and music intelligence services for streaming platforms and music applications.",
    provider: "Music Story",
    pricing: "enterprise",
    rating: 1,
    reviews: 0,
    features: ["Artist biographies", "Discography data", "Music metadata"],
    languages: ["REST API"],
    tags: ["music-metadata", "artist-biographies", "discographies"],
    category: "Metadata & Database"
  },
  {
    id: "musixmatch-api",
    name: "Musixmatch API",
    description: "World's largest lyrics catalog and API with 12M+ songs in 250+ languages, providing lyrics display, synchronization, search, translations, and mood analysis for music platforms.",
    provider: "Musixmatch S.p.A.",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["Lyrics display", "Synchronized lyrics", "Lyrics search"],
    languages: ["REST API", "iOS SDK", "Android SDK", "JavaScript"],
    tags: ["lyrics-api", "music-metadata", "synchronization"],
    category: "Lyrics & Text"
  },
  {
    id: "cyanite-api",
    name: "Cyanite API",
    description: "AI-powered music analysis platform providing automated tagging, similarity search, and mood detection for music catalogs, enabling advanced music discovery and recommendation systems.",
    provider: "Cyanite GmbH",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["Automated music tagging", "Similarity analysis", "Mood detection"],
    languages: ["REST API", "Python SDK"],
    tags: ["ai-analysis", "music-tagging", "similarity-search"],
    category: "AI & Analysis"
  },
  {
    id: "acrcloud-api",
    name: "ACRCloud API",
    description: "Leading automatic content recognition platform providing music identification, broadcast monitoring, and cover song detection APIs for apps, broadcasters, and music services worldwide.",
    provider: "ACRCloud",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: ["Music recognition", "Audio fingerprinting", "Cover song identification"],
    languages: ["Python", "PHP", "Java", "JavaScript"],
    tags: ["audio-recognition", "music-identification", "api"],
    category: "Music Recognition"
  },
  {
    id: "mlc-data-api",
    name: "The MLC Data Programs API",
    description: "Comprehensive data programs from The Mechanical Licensing Collective providing bulk access to musical works database and API services for the music industry.",
    provider: "The Mechanical Licensing Collective",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["Bulk data access", "Public Search API", "Musical works database"],
    languages: ["REST API", "DDEX", "BWARM"],
    tags: ["mechanical-licensing", "database", "bulk-data"],
    category: "Rights & Royalties"
  },
  {
    id: "spatial9-api",
    name: "Spatial9 AI - Charlie Labs 4 Music API",
    description: "Generative spatial audio technology platform creating immersive Ambisonics audio experiences for music and media applications.",
    provider: "Spatial9 AI",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["Generative spatial audio", "Ambisonics processing", "Immersive audio creation"],
    languages: [],
    tags: ["spatial-audio", "ambisonics", "generative-ai"],
    category: "Audio Processing"
  },
  {
    id: "musicbrainz-api",
    name: "MusicBrainz API",
    description: "Open music encyclopedia that collects music metadata and makes it available to the public.",
    provider: "MetaBrainz Foundation",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Music metadata", "Artist info", "Release data"],
    languages: ["REST", "JSON", "XML"],
    tags: ["metadata", "open-source", "encyclopedia"],
    category: "Metadata & Database"
  },
  {
    id: "deezer-api",
    name: "Deezer API",
    description: "Access Deezer music catalog, user data, and streaming capabilities.",
    provider: "Deezer",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: ["Track metadata", "User playlists", "Radio stations"],
    languages: ["REST", "JSON"],
    tags: ["streaming", "catalog", "playlists"],
    category: "Streaming & Playback"
  },
  {
    id: "soundcloud-api",
    name: "SoundCloud API",
    description: "Access SoundCloud tracks, users, playlists, and comments through their REST API.",
    provider: "SoundCloud",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: ["Track streaming", "User data", "Comments"],
    languages: ["REST", "JSON"],
    tags: ["streaming", "social", "uploads"],
    category: "Streaming & Playback"
  },
  {
    id: "apple-music-api",
    name: "Apple Music API",
    description: "Access Apple Music catalog, user library, and playlist data through MusicKit and Apple Music API.",
    provider: "Apple",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Catalog search", "User library", "Playlists"],
    languages: ["JavaScript", "Swift", "REST"],
    tags: ["streaming", "catalog", "playlists"],
    category: "Streaming & Playback"
  },
  {
    id: "youtube-music-api",
    name: "YouTube Music API",
    description: "Access YouTube Music data through the YouTube Data API v3.",
    provider: "Google",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: ["Video metadata", "Search", "Playlists"],
    languages: ["REST", "JSON"],
    tags: ["streaming", "video", "search"],
    category: "Streaming & Playback"
  },
  {
    id: "echo-nest-api",
    name: "Echo Nest API",
    description: "Music intelligence API providing audio analysis and music recommendation algorithms.",
    provider: "Echo Nest (Spotify)",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Audio analysis", "Tempo detection", "Key detection"],
    languages: ["REST", "JSON"],
    tags: ["analysis", "recommendations", "tempo"],
    category: "AI & Analysis"
  },
  {
    id: "gracenote-api",
    name: "Gracenote API",
    description: "Music recognition and metadata service with global music database.",
    provider: "Gracenote",
    pricing: "paid",
    rating: 0,
    reviews: 0,
    features: ["Music recognition", "Rich metadata", "Cover art"],
    languages: ["REST", "JSON"],
    tags: ["recognition", "metadata", "global"],
    category: "Music Recognition"
  },
  {
    id: "roex-api",
    name: "Roex API",
    description: "AI-driven audio production platform designed to make pro-grade mixing and mastering accessible via web, desktop, or API integrations.",
    provider: "Roex",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: ["Master full tracks to optimise loudness, tone, and width for a polished, release-ready sound", "Generate mastered previews before finalising your track", "Mix multitrack audio for a balanced and cohesive sound (up to 32 tracks)"],
    languages: ["Python"],
    tags: ["audio-processing", "synthesis", "effects"],
    category: "Audio Processing"
  },
  {
    id: "covers-ai-api",
    name: "Covers.ai API",
    description: "AI-powered tool tailored for music creators and marketers to instantly produce viral short-form music videos optimized for TikTok, Instagram Reels, and YouTube Shorts. Simply upload a track, select your visual style or brand preferences, and the platform generates multiple polished music video options—lyric visuals, mood-based visuals, or trend-driven clips—in minutes",
    provider: "Mayk.it",
    pricing: "paid",
    rating: 0,
    reviews: 0,
    features: [],
    languages: [],
    tags: [],
    category: "Video & Visual"
  },
  {
    id: "music-ai-enterprise-api",
    name: "Music.ai API",
    description: "Music.ai is an enterprise-grade AI audio platform offering a suite of advanced tools to streamline music, audio, and video workflows. Its core capabilities include high-precision stem separation, voice swapping, transcription and lyric alignment, chord/section detection, metadata tagging, mixing & mastering, and AI voice dubbing—all powered by ethical, scalable models.",
    provider: "Music.AI",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: [],
    languages: [],
    tags: ["api", "metadata", "audio-processing"],
    category: "AI & Analysis"
  },
  {
    id: "copyright-delta-api",
    name: "Copyright Delta API",
    description: "AI & Gaming Portal Opt Out & In, Register & License We connect rights controllers and owners with AI and gaming platforms through a single API.",
    provider: "Copyright Delta",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: [],
    languages: [],
    tags: ["api", "licensing", "rights"],
    category: "Rights & Royalties"
  },
  {
    id: "beatoven-api",
    name: "Beatoven API",
    description: "Empowering creators worldwide with AI-driven tools to make music creation more accessible.",
    provider: "Beatoven.ai",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: ["Text to music", "Video to music", "Automated metadata generation"],
    languages: [],
    tags: ["api", "metadata", "ai"],
    category: "AI & Generation"
  },
  {
    id: "kor-protocol-api",
    name: "KOR Protocol API",
    description: "KOR helps creators, fans, and developers build together using tools that protect IP, enable AI-powered remixing, and allow for transparent licensing and monetization on the blockchain.",
    provider: "Pixelynx",
    pricing: "enterprise",
    rating: 0,
    reviews: 0,
    features: ["manage IPs on-chain", "distribute IPs on-chain", "monetize IPs on-chain"],
    languages: [],
    tags: ["collaboration", "metadata", "token"],
    category: "Blockchain & Web3"
  },
  {
    id: "musicfetch-api",
    name: "MusicFetch API",
    description: "Fetch links metadata from any song, album or artist from over 30 different sources with one API call",
    provider: "MusicFetch",
    pricing: "freemium",
    rating: 0,
    reviews: 0,
    features: [],
    languages: ["Python", "TypeScript", "JavaScript"],
    tags: ["api", "metadata"],
    category: "Metadata & Database"
  },
  {
    id: "spotify-web-api",
    name: "Spotify Web API",
    description: "Access Spotify catalog data, manage user playlists, control playback, and get user listening data through a RESTful API.",
    provider: "Spotify",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Track metadata", "Playlist management", "User data"],
    languages: ["JavaScript", "Python", "Java", "C#"],
    tags: ["streaming", "playlists", "search"],
    category: "Streaming & Playback"
  },
  {
    id: "lastfm-api",
    name: "Last.fm API",
    description: "Access music metadata, scrobbling data, charts, and recommendations from one of the largest music databases.",
    provider: "Last.fm",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Music metadata", "User scrobbles", "Charts"],
    languages: ["JSON", "XML", "REST"],
    tags: ["metadata", "scrobbling", "charts"],
    category: "Metadata & Database"
  },
  {
    id: "web-audio-api",
    name: "Web Audio API",
    description: "Native browser API for processing and synthesizing audio in web applications.",
    provider: "W3C/Browser vendors",
    pricing: "free",
    rating: 0,
    reviews: 0,
    features: ["Audio synthesis", "Real-time effects", "Audio analysis"],
    languages: ["JavaScript"],
    tags: ["web-audio", "synthesis", "effects"],
    category: "Audio Processing"
  },
  {
    id: "dpm-network-api",
    name: "DPM Network Music Distribution API",
    description: "DPM Network Music Distribution does offer API integration as part of its distribution services for labels. This API integration allows labels to connect their music catalog directly to the DPM Network platform, streamlining the distribution process and making it easier to manage and update their releases.",
    provider: "DPM Network Music Distribution",
    pricing: "subscription",
    rating: 0,
    reviews: 0,
    features: ["White-Label Integration", "Direct DSP Delivery", "Full DDEX Support"],
    languages: ["JSON"],
    tags: ["api", "metadata", "audio-processing"],
    category: "Distribution & Sales"
  }
];

export const categories = [
  { name: "All", count: integrationsData.length, color: "bg-blue-500" },
  { name: "AI & Analysis", count: integrationsData.filter(i => i.category === "AI & Analysis").length, color: "bg-purple-500" },
  { name: "Audio Processing", count: integrationsData.filter(i => i.category === "Audio Processing").length, color: "bg-green-500" },
  { name: "Streaming & Playback", count: integrationsData.filter(i => i.category === "Streaming & Playback").length, color: "bg-red-500" },
  { name: "Music Recognition", count: integrationsData.filter(i => i.category === "Music Recognition").length, color: "bg-yellow-500" },
  { name: "Metadata & Database", count: integrationsData.filter(i => i.category === "Metadata & Database").length, color: "bg-indigo-500" },
  { name: "Rights & Royalties", count: integrationsData.filter(i => i.category === "Rights & Royalties").length, color: "bg-pink-500" },
  { name: "Events & Concerts", count: integrationsData.filter(i => i.category === "Events & Concerts").length, color: "bg-cyan-500" },
  { name: "Distribution & Sales", count: integrationsData.filter(i => i.category === "Distribution & Sales").length, color: "bg-orange-500" },
  { name: "Lyrics & Text", count: integrationsData.filter(i => i.category === "Lyrics & Text").length, color: "bg-teal-500" },
  { name: "AI & Generation", count: integrationsData.filter(i => i.category === "AI & Generation").length, color: "bg-violet-500" },
  { name: "AI & Voice", count: integrationsData.filter(i => i.category === "AI & Voice").length, color: "bg-rose-500" },
  { name: "AI & Search", count: integrationsData.filter(i => i.category === "AI & Search").length, color: "bg-emerald-500" },
  { name: "Video & Visual", count: integrationsData.filter(i => i.category === "Video & Visual").length, color: "bg-amber-500" },
  { name: "Blockchain & Web3", count: integrationsData.filter(i => i.category === "Blockchain & Web3").length, color: "bg-slate-500" },
];
