project_id = "ixkkrousepsiorwlaycp"

[functions.generate-merch-design]
verify_jwt = true

[functions.voice-management]
verify_jwt = false

[functions.podcast-generator]
verify_jwt = true

[functions.cerebras-stream]
verify_jwt = true

[functions.cerebras-research]
verify_jwt = true

[functions.cerebras-stream]
verify_jwt = true

[functions.venue-ai-search]
verify_jwt = false

[functions.generate-booking-email]
verify_jwt = true

[functions.generate-contract]
verify_jwt = true

[functions.generate-invoice]
verify_jwt = true

[functions.generate-event-asset]
verify_jwt = true

[functions.research-sessions]
verify_jwt = true

[functions.manage-user-secrets]
verify_jwt = true

[functions.get-dashboard-stats]
verify_jwt = true

[functions.get-gig-revenue]
verify_jwt = true
