project_id = "ixkkrousepsiorwlaycp"

[functions.voice-management]
verify_jwt = false

[functions.podcast-generator]
verify_jwt = false

[functions.cerebras-research]
verify_jwt = false

[functions.venue-ai-search]
verify_jwt = false

[functions.generate-booking-email]
verify_jwt = true